namespace GoldenStore.Models
{

    public class MetalModel
    {
        public bool success { get; set; }
        public int timestamp { get; set; }
        public string date { get; set; }
        public string _base { get; set; }
        public Rates[] rates { get; set; }
        public string unit { get; set; }
    }

    public class Rates
    {
        public float AED { get; set; }
        public float AFN { get; set; }
        public float ALL { get; set; }
        public float AMD { get; set; }
        public float ANG { get; set; }
        public float AOA { get; set; }
        public float ARS { get; set; }
        public float AWG { get; set; }
        public float AZN { get; set; }
        public float BAM { get; set; }
        public float BBD { get; set; }
        public float BDT { get; set; }
        public float BGN { get; set; }
        public float BHD { get; set; }
        public float BIF { get; set; }
        public int BMD { get; set; }
        public float BND { get; set; }
        public float BOB { get; set; }
        public float BRL { get; set; }
        public float BSD { get; set; }
        public float BTN { get; set; }
        public float BWP { get; set; }
        public float BYN { get; set; }
        public float BYR { get; set; }
        public float BZD { get; set; }
        public float CAD { get; set; }
        public float CDF { get; set; }
        public float CHF { get; set; }
        public float CLF { get; set; }
        public float CLP { get; set; }
        public float CNY { get; set; }
        public float COP { get; set; }
        public float CRC { get; set; }
        public int CUC { get; set; }
        public float CVE { get; set; }
        public float CZK { get; set; }
        public int DJF { get; set; }
        public float DKK { get; set; }
        public float DOP { get; set; }
        public float DZD { get; set; }
        public float EGP { get; set; }
        public float ETB { get; set; }
        public float EUR { get; set; }
        public float FJD { get; set; }
        public float FKP { get; set; }
        public float GBP { get; set; }
        public float GEL { get; set; }
        public float GHS { get; set; }
        public float GIP { get; set; }
        public float GMD { get; set; }
        public float GNF { get; set; }
        public float GTQ { get; set; }
        public float GYD { get; set; }
        public float HKD { get; set; }
        public float HNL { get; set; }
        public float HRK { get; set; }
        public float HTG { get; set; }
        public float HUF { get; set; }
        public float IDR { get; set; }
        public float ILS { get; set; }
        public float INR { get; set; }
        public float IQD { get; set; }
        public float ISK { get; set; }
        public float JMD { get; set; }
        public float JOD { get; set; }
        public float JPY { get; set; }
        public float KES { get; set; }
        public float KGS { get; set; }
        public float KHR { get; set; }
        public float KMF { get; set; }
        public float KRW { get; set; }
        public float KWD { get; set; }
        public float KYD { get; set; }
        public float KZT { get; set; }
        public float LAK { get; set; }
        public float LBP { get; set; }
        public float LKR { get; set; }
        public float LRD { get; set; }
        public float LSL { get; set; }
        public float LYD { get; set; }
        public float MAD { get; set; }
        public float MDL { get; set; }
        public float MGA { get; set; }
        public float MKD { get; set; }
        public float MMK { get; set; }
        public float MNT { get; set; }
        public float MOP { get; set; }
        public float MUR { get; set; }
        public float MVR { get; set; }
        public int MWK { get; set; }
        public float MXN { get; set; }
        public float MYR { get; set; }
        public float MZN { get; set; }
        public float NAD { get; set; }
        public float NGN { get; set; }
        public float NIO { get; set; }
        public float NOK { get; set; }
        public float NPR { get; set; }
        public float NZD { get; set; }
        public float OMR { get; set; }
        public float PAB { get; set; }
        public float PEN { get; set; }
        public float PGK { get; set; }
        public float PHP { get; set; }
        public float PKR { get; set; }
        public float PLN { get; set; }
        public float PYG { get; set; }
        public float QAR { get; set; }
        public float RON { get; set; }
        public float RSD { get; set; }
        public float RWF { get; set; }
        public float SAR { get; set; }
        public float SBD { get; set; }
        public float SCR { get; set; }
        public float SEK { get; set; }
        public float SHP { get; set; }
        public float SLL { get; set; }
        public float SRD { get; set; }
        public float SSP { get; set; }
        public float STD { get; set; }
        public float SVC { get; set; }
        public float SZL { get; set; }
        public float THB { get; set; }
        public float TJS { get; set; }
        public float TMT { get; set; }
        public float TND { get; set; }
        public float TOP { get; set; }
        public float TRY { get; set; }
        public float TTD { get; set; }
        public float TWD { get; set; }
        public float TZS { get; set; }
        public float UAH { get; set; }
        public float UGX { get; set; }
        public float UYU { get; set; }
        public float UZS { get; set; }
        public float VES { get; set; }
        public int VND { get; set; }
        public float VUV { get; set; }
        public float WST { get; set; }
        public float XAF { get; set; }
        public float XAG { get; set; }
        public float XAU { get; set; }
        public float XCD { get; set; }
        public float XDR { get; set; }
        public float XOF { get; set; }
        public float XPD { get; set; }
        public float XPF { get; set; }
        public float XPT { get; set; }
        public float YER { get; set; }
        public float ZAR { get; set; }
        public float ZMW { get; set; }
        public float JEP { get; set; }
        public float GGP { get; set; }
        public float IMP { get; set; }
        public float CNH { get; set; }
        public float ZWL { get; set; }
        public float VEF { get; set; }
        public float SGD { get; set; }
        public float AUD { get; set; }
        public int USD { get; set; }
        public float BTC { get; set; }
        public float BCH { get; set; }
        public float ETH { get; set; }
        public float LTC { get; set; }
        public float LINK { get; set; }
        public float XRP { get; set; }
        public float XLM { get; set; }
        public float UNI { get; set; }
        public float ADA { get; set; }
        public float MTL { get; set; }
        public float ERN { get; set; }
        public float XRH { get; set; }
        public float RUTH { get; set; }
        public float XCU { get; set; }
        public float ALU { get; set; }
        public float NI { get; set; }
        public float ZNC { get; set; }
        public float TIN { get; set; }
        public float LCO { get; set; }
        public float IRD { get; set; }
        public float LEAD { get; set; }
        public float IRON { get; set; }
        public float LBXAUAM { get; set; }
        public float LBXAUPM { get; set; }
        public float LBXAG { get; set; }
        public float LBXPTAM { get; set; }
        public float LBXPTPM { get; set; }
        public float LBXPDAM { get; set; }
        public float LBXPDPM { get; set; }
        public float LMEALU { get; set; }
        public float LMEXCU { get; set; }
        public float LMEZNC { get; set; }
        public float LMENI { get; set; }
        public float LMELEAD { get; set; }
        public float LMETIN { get; set; }
        public float URANIUM { get; set; }
        public float STEELSC { get; set; }
        public float STEELRE { get; set; }
        public float STEELHR { get; set; }
        public float BRONZE { get; set; }
        public float MG { get; set; }
        public float OSMIUM { get; set; }
        public float RHENIUM { get; set; }
        public float INDIUM { get; set; }
        public float MO { get; set; }
        public float TUNGSTEN { get; set; }
        public float LITHIUM { get; set; }
        public float XAUAHME { get; set; }
        public float XAUBANG { get; set; }
        public float XAUCHEN { get; set; }
        public float XAUCOIM { get; set; }
        public float XAUDELH { get; set; }
        public float XAUHYDE { get; set; }
        public float XAUKOCH { get; set; }
        public float XAUKOLK { get; set; }
        public float XAUMUMB { get; set; }
        public float XAUSURA { get; set; }
        public float ANTIMONY { get; set; }
        public float LTL { get; set; }
        public float LVL { get; set; }
        public float RUB { get; set; }
        public float BITUMEN { get; set; }
        public float GALLIUM { get; set; }
        public float MN { get; set; }
        public float ND { get; set; }
        public float TE { get; set; }
        public float XAGAHME { get; set; }
        public float XAGBANG { get; set; }
        public float XAGCHEN { get; set; }
        public float XAGCOIM { get; set; }
        public float XAGDELH { get; set; }
        public float XAGHYDE { get; set; }
        public float XAGKOCH { get; set; }
        public float XAGKOLK { get; set; }
        public float XAGMUMB { get; set; }
        public float XAGSURA { get; set; }
    }

}
